version: "3.7"

services:
  php:
    build:
      context: ./Dockerfiles/centos 
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "4000:80"
    volumes:
      - ./html:/var/www/html

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./Dockerfiles/mysql/data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"